-- Run this on existing Supabase projects to extend financial_reports
-- with ~50 metrics for BI dashboards.

ALTER TABLE financial_reports
    ADD COLUMN IF NOT EXISTS cogs NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS gross_profit NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS financial_income NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS financial_expense NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS interest_expense NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS selling_expense NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS general_admin_expense NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS operating_profit NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS other_income NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS other_expense NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS profit_before_tax NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS parent_profit_after_tax NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS minority_profit NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS depreciation_amortization NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS ebit NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS ebitda NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS cash_and_cash_equivalents NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS short_term_investments NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS short_term_receivables NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS inventory NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS other_current_assets NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS total_current_assets NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS long_term_receivables NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS fixed_assets NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS investment_properties NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS long_term_assets NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS short_term_debt NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS accounts_payable NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS short_term_liabilities NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS total_short_term_liabilities NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS long_term_debt NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS total_long_term_liabilities NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS owner_equity NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS retained_earnings NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS share_capital NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS total_equity_and_liabilities NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS cash_flow_operating NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS cash_flow_investing NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS cash_flow_financing NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS net_cash_flow NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS capex NUMERIC(20, 2),
    ADD COLUMN IF NOT EXISTS gross_margin NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS operating_margin NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS net_margin NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS roe NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS roa NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS debt_to_equity NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS current_ratio NUMERIC(20, 6),
    ADD COLUMN IF NOT EXISTS asset_turnover NUMERIC(20, 6);

ALTER TABLE financial_reports
    ALTER COLUMN eps TYPE NUMERIC(20, 4);
